import Head from "next/head";
import { Montserrat } from "next/font/google";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import "../styles/globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});
export const metadata = {
  title: "Ahmed | Portfolio",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: PropsLayout) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${montserrat.variable} font-mont bg-light w-full min-h-screen flex flex-col justify-center items-center`}
        >
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
